<?php

declare(strict_types=1);

$mefi = 'MeFi';
$metaFilter = config('app.name');

use App\Enums\RouteNameEnum;

return [
    'ask' => [
        'name' => 'Ask ' . $metaFilter,
        'nickname' => 'AskMeFi',
        'logoFilename' => 'ask-mefi.png',
        'whiteText' => 'Ask',
        'greenText' => $metaFilter,
        'tagline' => 'querying the hive mind',
        'subdomain' => 'ask',
        'route' => RouteNameEnum::AskPostIndex,
        'view' => 'posts.index',
        'inDropdown' => false,
        'inFooterNav' => true,
        'footerNavigationSortOrder' => 2,
        'globalNavigationSortOrder' => 2,
        'hasTheme' => true,
    ],
    'bestof' => [
        'name' => 'Best Of ',
        'nickname' => 'Best Of',
        'whiteText' => null,
        'greenText' => null,
        'tagline' => 'Highlighting the best bits from the MetaFilter universe',
        'subdomain' => 'bestof',
        'route' => RouteNameEnum::BestOfHomeIndex,
        'view' => 'bestof.home.index',
        'inDropdown' => true,
        'inFooterNav' => false,
        'footerNavigationSortOrder' => 9,
        'globalNavigationSortOrder' => 9,
        'hasTheme' => true,
    ],
    'chat' => [
        'name' => 'MetaChat',
        'nickname' => 'Chat',
        'whiteText' => $metaFilter,
        'greenText' => 'Chat',
        'tagline' => 'talk about ' . $metaFilter,
        'subdomain' => 'chat',
        'route' => RouteNameEnum::ChatHomeIndex,
        'view' => 'chat.home.index',
        'inDropdown' => true,
        'inFooterNav' => false,
        'footerNavigationSortOrder' => 0,
        'globalNavigationSortOrder' => 11,
        'hasTheme' => false,
    ],
    'fanfare' => [
        'name' => 'FanFare',
        'logoFilename' => 'mefi-fanfare.png',
        'whiteText' => 'Fan',
        'greenText' => 'Fare',
        'tagline' => 'overthinking entertainment',
        'subdomain' => 'fanfare',
        'route' => RouteNameEnum::FanfarePostIndex,
        'view' => 'posts.index',
        'inDropdown' => false,
        'inFooterNav' => true,
        'footerNavigationSortOrder' => 3,
        'globalNavigationSortOrder' => 3,
        'hasTheme' => true,
    ],
    'faq' => [
        'name' => 'FAQ',
        'subdomain' => 'faq',
        'route' => RouteNameEnum::FaqIndex,
        'view' => 'faq.index',
        'inDropdown' => false,
        'inFooterNav' => false,
        'footerNavigationSortOrder' => 0,
        'globalNavigationSortOrder' => 0,
        'hasTheme' => false,
    ],
    'irl' => [
        'name' => 'MeFi IRL',
        'nickname' => 'IRL',
        'logoFilename' => 'mefi-irl.png',
        'whiteText' => 'MeFi',
        'greenText' => 'IRL',
        'tagline' => 'get out. meet people.',
        'subdomain' => 'irl',
        'route' => RouteNameEnum::IrlPostIndex,
        'view' => 'posts.index',
        'inDropdown' => false,
        'inFooterNav' => true,
        'footerNavigationSortOrder' => 7,
        'globalNavigationSortOrder' => 7,
        'hasTheme' => true,
    ],
    'jobs' => [
        'name' => 'Jobs',
        'logoFilename' => 'mefi-jobs.png',
        'whiteText' => 'MeFi',
        'greenText' => 'Jobs',
        'tagline' => 'all work and no play',
        'subdomain' => 'jobs',
        'route' => RouteNameEnum::JobsPostIndex,
        'view' => 'posts.index',
        'inDropdown' => false,
        'inFooterNav' => true,
        'footerNavigationSortOrder' => 6,
        'globalNavigationSortOrder' => 6,
        'hasTheme' => true,
    ],
    'labs' => [
        'name' => 'Labs',
        'whiteText' => 'MeFi',
        'greenText' => 'Labs',
        'tagline' => 'digital experimentation',
        'subdomain' => 'labs',
        'route' => RouteNameEnum::LabsHomeIndex,
        'view' => 'labs.home.index',
        'inDropdown' => true,
        'inFooterNav' => false,
        'footerNavigationSortOrder' => 0,
        'globalNavigationSortOrder' => 12,
        'hasTheme' => false,
    ],
    'mail' => [
        'name' => 'Mall',
        'whiteText' => 'MeFi',
        'greenText' => 'Mall',
        'subdomain' => 'mall',
        'route' => RouteNameEnum::MallHomeIndex,
        'view' => 'mall.home.index',
        'inDropdown' => true,
        'inFooterNav' => false,
        'footerNavigationSortOrder' => 0,
        'globalNavigationSortOrder' => 13,
        'hasTheme' => false,
    ],
    'mall' => [
        'name' => 'Mall',
        'whiteText' => 'MeFi',
        'greenText' => 'Mall',
        'subdomain' => 'mall',
        'route' => RouteNameEnum::MallHomeIndex,
        'view' => 'mall.home.index',
        'inDropdown' => true,
        'inFooterNav' => false,
        'footerNavigationSortOrder' => 0,
        'globalNavigationSortOrder' => 13,
        'hasTheme' => false,
    ],
    'metatalk' => [
        'name' => 'MetaTalk',
        'logoFilename' => 'metatalk.png',
        'whiteText' => 'Meta',
        'greenText' => 'Talk',
        'tagline' => 'feature requests, bugs, etc.',
        'subdomain' => 'metatalk',
        'route' => RouteNameEnum::MetaTalkPostIndex,
        'view' => 'posts.index',
        'inDropdown' => false,
        'inFooterNav' => true,
        'footerNavigationSortOrder' => 8,
        'globalNavigationSortOrder' => 8,
        'hasTheme' => true,
    ],
    'music' => [
        'name' => 'Music',
        'logoFilename' => 'mefi-music.png',
        'whiteText' => 'MeFi',
        'greenText' => 'Music',
        'tagline' => 'rock and/or roll',
        'subdomain' => 'music',
        'route' => RouteNameEnum::MusicPostIndex,
        'view' => 'posts.index',
        'inDropdown' => false,
        'inFooterNav' => true,
        'footerNavigationSortOrder' => 5,
        'globalNavigationSortOrder' => 5,
        'hasTheme' => true,
    ],
    'podcast' => [
        'name' => 'Podcast',
        'logoFilename' => 'mefi-podcast.png',
        'whiteText' => $mefi,
        'greenText' => 'Podcast',
        'tagline' => 'best of the website',
        'subdomain' => 'podcast',
        'route' => RouteNameEnum::PodcastPostIndex,
        'view' => 'posts.index',
        'inDropdown' => true,
        'inFooterNav' => true,
        'footerNavigationSortOrder' => 10,
        'globalNavigationSortOrder' => 10,
        'hasTheme' => false,
    ],
    'projects' => [
        'name' => 'Projects',
        'logoFilename' => 'mefi-projects.png',
        'whiteText' => 'MeFi',
        'greenText' => 'Projects',
        'tagline' => 'where self-links rule',
        'subdomain' => 'projects',
        'route' => RouteNameEnum::ProjectsPostIndex,
        'view' => 'posts.index',
        'inDropdown' => false,
        'inFooterNav' => false,
        'footerNavigationSortOrder' => 4,
        'globalNavigationSortOrder' => 4,
        'hasTheme' => true,
    ],
    'www' => [
        'name' => 'MetaFilter',
        'logoFilename' => 'metafilter.png',
        'whiteText' => 'Meta',
        'greenText' => 'Filter',
        'tagline' => 'community weblog',
        'subdomain' => 'www',
        'route' => RouteNameEnum::MetaFilterPostIndex,
        'view' => 'posts.index',
        'inDropdown' => false,
        'inFooterNav' => false,
        'footerNavigationSortOrder' => 1,
        'globalNavigationSortOrder' => 1,
        'hasTheme' => true,
    ],
];
