<?php

declare(strict_types=1);

return [
    'abo',
    'beaner',
    'boong',
    'chick with a dick',
    'chicks with dicks',
    'chinaman',
    'chinamen',
    'ching chong',
    'coolie',
    'dago',
    'golliwog',
    'gollywog',
    'gook',
    'gyp',
    'gypped',
    'gypsies',
    'gypsy',
    'half-breed',
    'half-caste',
    'halfbreed',
    'halfcaste',
    'injun',
    'jap',
    'kaffir',
    'kike',
    'ladyboy',
    'lubra',
    'nigga',
    'nigger',
    'paki',
    'picaninnies',
    'picaninny',
    'pickaninnies',
    'pickaninny',
    'raghead',
    'redskin',
    'shemale',
    'slopehead',
    'spic',
    'squaw',
    'tar babies',
    'tar baby',
    'tar-babies',
    'tar-baby',
    'tarbabies',
    'tarbaby',
    'towelhead',
    'tzigane',
    'wetback',
    'wog',
    'wop',
];
